### ISSUE TITLE
mobi files for your Kindle

### ISSUE THREAD

**Issue by lexrus** [faisalmemon/ios-crash-dump-analysis-book#7]
![IMG_1474](https://user-images.githubusercontent.com/219689/111934683-dda67f00-8afc-11eb-84b9-24b7f8112a9a.jpg)

[iOS Crash Dump Analysis 中文版.mobi.zip](https://github.com/faisalmemon/ios-crash-dump-analysis-book/files/6179148/iOS.Crash.Dump.Analysis.mobi.zip)
[iOS Crash Dump Analysis.mobi.zip](https://github.com/faisalmemon/ios-crash-dump-analysis-book/files/6179149/iOS.Crash.Dump.Analysis.mobi.zip)

**Comment by faisalmemon** [comment]
I get the problem on my simulator with the above files:
Kindle Previewer does not support this file, which has either been created using an older version of KindleGen or a third party application. We recommend using EPUB or DOCX format directly for previewing and publishing your book on Kindle.

for the Chinese and English version of the book.  I have 3.51.0 of the Kindle Previewer.

I wasn't able to generate the chinese version cleanly.


Can you let me know how your version compares with what I am currently able to produce ([foo.zh.epub.zip](https://github.com/faisalmemon/ios-crash-dump-analysis-book/files/6180583/foo.zh.epub.zip)) please.  I get errors during building:

```
pandoc-citeproc: reference iosOnMac你可以进行如下操作 not found
Cleaning up csl indent remarks
Indexing pass 0
Indexing pass 1
Indexing pass 2
Check for errors
boo.zh.pass.0.log:119:! Package inputenc Error: Unicode character 。 (U+3002)
boo.zh.pass.0.log:134:!  ==> Fatal error occurred, no output PDF file produced!
boo.zh.pass.1.log:119:! Package inputenc Error: Unicode character 。 (U+3002)
boo.zh.pass.1.log:134:!  ==> Fatal error occurred, no output PDF file produced!
boo.zh.pass.2.log:119:! Package inputenc Error: Unicode character 。 (U+3002)
boo.zh.pass.2.log:134:!  ==> Fatal error occurred, no output PDF file produced!
Processing foo.zh.epub
pandoc-citeproc: reference iosOnMac你可以进行如下操作 not found
Processing foo.zh.docx
pandoc-citeproc: reference iosOnMac你可以进行如下操作 not found
Constructing github pages
```

Any help with getting a good version of the Chinese edition built for .epub format would be much appreciated.  Thanks!

**Comment by lexrus** [comment]
Hi @faisalmemon 

AFAIK: epub is not Kindle device compatible, instead it works well in Books.app(a.k.a. iBooks). The native format for Kindle, I mean a real hardware device, is epub.
FYI. I use https://calibre-ebook.com to covert the epub to mobi.

**Comment by faisalmemon** [comment]
As an author on the Kindle Direct Publishing platform, we get special tools to create and check our Kindle books.  EPUB is the preferred input source format for their tools, and it generates .mobi files and other format files as output.  I'd like to publish what I have but I don't know if the book has been correctly generated given my above errors.
[foo.zh.mobi.zip](https://github.com/faisalmemon/ios-crash-dump-analysis-book/files/6180930/foo.zh.mobi.zip) is the same EPUB file but generated with Amazon's tools (instead of the calibre tool).  Can you compare this file with your file, please.  I'd like to know if it has any flaws.  For example, what is presented for 你可以进行如下操作 in the book?

**Comment by lexrus** [comment]
Got you. I don't even know that until now.
There's no "你可以进行如下操作" in both books I'm afraid.

They have 3 differences in my Kindle:
1. Your mobi is 13.6MB, mine 2.8MB
2. Minor line height and font weight difference
3. Your mobi has a cover page in the home page

I guess we should stick on the official tool. I just think it's convenient for Kindle users to have pre generated mobi files to download.

Anyway, this book is awesome. Thank you for your great work.
